config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'welcome/index'
  resources :articles 
  #
  #  get "/articles" index
  #  post "/articles" create
  #  delet "/articles" delete
  #  get "/articles/:id" show
  #  get "articles/:new" new 
  #  get "articles/:id/edit" edit
  #  path "articles/:id" update
  #  post "/articles/:id" update
  #

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord 
    validates :title, presence:true,uniqueness:true
    validates :body, presence:true,length: {minimum:20}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    #get /articles
    def index
       @articles = Article.all
    end
    #get /articles/id
    def show
       @article = Article.find(params[:id])
    end
    #get /articles/new
    def new
      @article = Article.new
   end
   #post /articles
   def create
      @article=Article.new(article_params)
      
      if @article.save
         redirect_to @article
      else
         render :new
      end    
   end
   def destroy
      @article= Article.find(params[:id])
      @article.destroy
      redirect_to articles_path
   end

   def edit
      @article = Article.find(params[:id])
   
   end

   def update
      @article = Article.find(params[:id])

      if@article.update(article_params)
         redirect_to @article
      else
         render :edit
      end
   end
   

   private

   def article_params
      params.require(:article).permit(:title,:body)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<h1><%= name%> articulo</h1>
<%= form_for (@article) do |f| %>
<% @article.errors.full_messages.each do |msj| %>
    <div class="be-red white top-space">*<%= msj%></div>               
<% end %>
<div class= "field">
   <%= f.text_field :title, placeholder:"Titulo",class:"form-control" %>
</div>
<div class="field">
    <%= f.text_area :body,placeholder:"Escriba aqui su texto", style:"height:250px" ,class:"form-control" %>
</div>
<div class="field">
    <%= f.submit "Guardar",class:"btn be-red white large-padding"%>
</div>    
<% end %>

app/views/articles/edit.html.erb
<div style= "width: 80%;margin:0 auto;">
         <%= render "form",name:"Editar" %>     
    
    </div>
    
    

app/views/articles/index.html.erb
<% @articles.each do |article| %> 
<h1> 
    <%= link_to article.title,article%>
</h1>
<div>
    <%= article.body %> - <%=link_to "Eliminar",article,method: :delete %>
</div>
<hr>
<%end %>

app/views/articles/new.html.erb
<div style= "width: 80%;margin:0 auto;">
        <%= render "form",name:"Crear"%>     


</div>

app/views/articles/show.html.erb
<h1> 
    <%= @article.title%>
</h1>
<div>
    <%= @article.body %>
</div>
<div>
    <hr>
    <%= link_to "Editar",edit_article_path(@article)%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <header>
          <nav class="be-red white large-padding">
              <ul class="no-list row center-xs ">
                  <ul class="col-md">
                     <%= link_to "Inicio", root_path %>
                  </ul>
                  <ul class="col-md">
                    <%= link_to "Diseño", root_path %>  
                  </ul>
                  <ul class="col-md">
                    <%= link_to "Programacion", root_path %>  
                  </ul>
                  <ul class="col-md">
                    <%= link_to "Tecnologia", root_path %>  
                  </ul>
                  <ul class="col-md">
                    <% if user_signed_in?  %>
                    <ul>
                    <%= link_to "Cerrar Seccion",destroy_user_session_path,method: :delete %>
                    </ul>  
                    <% end %>
                    
                  </ul>
              </ul>
          </nav>
      </header>
        <p class="notice"><%= notice%></p>
        <p class="alert"><%= alert%></p>
    <%= yield %>
	
  </body>
</html>